services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: mini-marketplace-app
    container_name: mini-marketplace-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: mini-marketplace-nginx
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: mini-marketplace-postgres
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: mini_marketplace
      POSTGRES_USER: mini_marketplace
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mini-marketplace-redis
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mini-marketplace-mailpit
    ports:
      - "${FORWARD_MAILPIT_PORT:-8025}:8025"

  worker:
    image: mini-marketplace-app
    container_name: mini-marketplace-worker
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php artisan queue:work redis --sleep=1 --tries=3 --timeout=60
    depends_on:
      - app
      - redis
      - postgres
    profiles:
      - workers

volumes:
  postgres-data:

